### ISSUE TITLE
[Req] Clarify license

### ISSUE THREAD

**Issue by xiota** [paulrouget/static-filepicker#1]
Please clarify the license.  Notably, this project is required for VDHCoApp to function.  So a compatible license would be needed.  Thank you.

**Comment by paulrouget** [comment]
Thanks. Done.

**Comment by xiota** [comment]
Thank you for updating...  Don't know where else to ask.  Hope you don't mind...  Seems this program is made specifically as a helper for VDHCoApp.  Will there be more info (like a readme) about what it does and whether it would be useful for other apps?
